# Generated by Django 4.2.7 on 2025-12-29 12:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(help_text='DNS, IP o nombre del contenedor Docker', max_length=255)),
                ('container_name', models.CharField(blank=True, help_text='Nombre del contenedor Docker (si es diferente del host)', max_length=255, null=True)),
                ('rcon_port', models.IntegerField(default=25575)),
                ('rcon_password', models.CharField(max_length=255)),
                ('minecraft_data_path', models.CharField(default='/data', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Servidor público (cualquiera puede conectarse)')),
                ('is_hidden', models.BooleanField(default=False, help_text='Servidor oculto (solo visible en misma red/VPN)')),
                ('auth_mode', models.CharField(choices=[('whitelist', 'Solo Whitelist'), ('database', 'Base de Datos (usuarios y contraseñas)'), ('both', 'Whitelist + Base de Datos'), ('public', 'Público (sin autenticación)')], default='whitelist', help_text='Modo de autenticación del servidor', max_length=20)),
                ('enable_whitelist', models.BooleanField(default=True, help_text='Habilitar whitelist en el servidor')),
                ('online_mode', models.BooleanField(default=False, help_text='Modo online (verifica con Mojang). Si False, permite clientes no premium')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En progreso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='server.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Comentario interno (no visible para el creador)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='server.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('players_online', models.IntegerField(default=0)),
                ('players_max', models.IntegerField(default=0)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.BigIntegerField(blank=True, null=True)),
                ('memory_max', models.BigIntegerField(blank=True, null=True)),
                ('disk_usage', models.BigIntegerField(blank=True, null=True)),
                ('disk_total', models.BigIntegerField(blank=True, null=True)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('network_in', models.BigIntegerField(blank=True, null=True)),
                ('network_out', models.BigIntegerField(blank=True, null=True)),
                ('tps', models.FloatField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='server.server')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='ServerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('player_join', 'Jugador conectado'), ('player_leave', 'Jugador desconectado'), ('server_start', 'Servidor iniciado'), ('server_stop', 'Servidor detenido'), ('server_crash', 'Servidor crasheado'), ('backup_completed', 'Backup completado'), ('backup_failed', 'Backup fallido'), ('plugin_enabled', 'Plugin habilitado'), ('plugin_disabled', 'Plugin deshabilitado'), ('warning', 'Advertencia'), ('error', 'Error')], max_length=50)),
                ('message', models.TextField()),
                ('player_name', models.CharField(blank=True, max_length=16, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='server.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('failed_login', 'Login fallido'), ('successful_login', 'Login exitoso'), ('suspicious_activity', 'Actividad sospechosa'), ('rate_limit_exceeded', 'Rate limit excedido'), ('ip_blocked', 'IP bloqueada'), ('unauthorized_access', 'Acceso no autorizado')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='server.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Acción a limitar (ej: login, command)', max_length=50)),
                ('max_requests', models.IntegerField(default=10)),
                ('time_window', models.IntegerField(default=60, help_text='Ventana de tiempo en segundos')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_rules', to='server.server')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(db_index=True, max_length=16)),
                ('metric', models.CharField(help_text='Métrica (ej: playtime, deaths, kills)', max_length=50)),
                ('value', models.FloatField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='server.server')),
            ],
        ),
        migrations.CreateModel(
            name='MinecraftUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password_hash', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minecraft_users', to='server.server')),
            ],
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist', to='server.server')),
            ],
        ),
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_blacklist', to='server.server')),
            ],
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('hourly', 'Cada hora'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='daily', max_length=20)),
                ('time', models.TimeField(help_text='Hora de ejecución (para daily/weekly/monthly)')),
                ('day_of_week', models.IntegerField(blank=True, help_text='Día de la semana (0=Lunes, 6=Domingo)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Día del mes (1-31)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_backups', models.IntegerField(default=10, help_text='Máximo de backups a mantener')),
                ('storage_type', models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], default='local', max_length=20)),
                ('s3_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='server.server')),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('world_size', models.BigIntegerField(blank=True, null=True)),
                ('player_count', models.IntegerField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='server.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserServerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('moderator', 'Moderador'), ('viewer', 'Visualizador')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'server')},
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['server', 'status', 'priority'], name='server_tick_server__d38e00_idx'),
        ),
        migrations.AddIndex(
            model_name='serverstatistic',
            index=models.Index(fields=['server', 'timestamp'], name='server_serv_server__2e3b59_idx'),
        ),
        migrations.AddIndex(
            model_name='serverevent',
            index=models.Index(fields=['server', 'event_type', 'created_at'], name='server_serv_server__6aa0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['server', 'log_type', 'created_at'], name='server_secu_server__14e3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['ip_address', 'created_at'], name='server_secu_ip_addr_24193e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelimitrule',
            unique_together={('server', 'action')},
        ),
        migrations.AddIndex(
            model_name='playerranking',
            index=models.Index(fields=['server', 'metric', 'value'], name='server_play_server__e3005f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerranking',
            unique_together={('server', 'player_name', 'metric')},
        ),
        migrations.AddIndex(
            model_name='minecraftuser',
            index=models.Index(fields=['server', 'username'], name='server_mine_server__fc546e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='minecraftuser',
            unique_together={('server', 'username')},
        ),
        migrations.AddIndex(
            model_name='ipwhitelist',
            index=models.Index(fields=['server', 'ip_address'], name='server_ipwh_server__b277c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ipwhitelist',
            unique_together={('server', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['server', 'ip_address', 'expires_at'], name='server_ipbl_server__afd707_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ipblacklist',
            unique_together={('server', 'ip_address')},
        ),
        migrations.AlterUniqueTogether(
            name='backupschedule',
            unique_together={('server', 'name')},
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['server', 'status', 'created_at'], name='server_back_server__1d8e02_idx'),
        ),
    ]
