# Generated by Django 4.2.7 on 2025-12-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_userpreference_serversession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Versión de Minecraft (ej: 1.20.1, 1.19.4)', max_length=20, unique=True)),
                ('display_name', models.CharField(help_text='Nombre para mostrar (ej: 1.20.1 - Latest)', max_length=50)),
                ('is_latest', models.BooleanField(default=False, help_text='¿Es la versión más reciente?')),
                ('is_stable', models.BooleanField(default=True, help_text='¿Es una versión estable?')),
                ('is_supported', models.BooleanField(default=True, help_text='¿Está soportada actualmente?')),
                ('server_types', models.JSONField(default=list, help_text="Tipos de servidor compatibles: ['vanilla', 'fabric', 'forge', 'bukkit', 'spigot', 'paper']")),
                ('release_date', models.DateField(blank=True, help_text='Fecha de lanzamiento', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre esta versión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Versión de Minecraft',
                'verbose_name_plural': 'Versiones de Minecraft',
                'ordering': ['-is_latest', '-version'],
            },
        ),
        migrations.AddField(
            model_name='server',
            name='additional_mods',
            field=models.JSONField(blank=True, default=list, help_text='Lista de mods adicionales a instalar (nombres de archivos)'),
        ),
        migrations.AddField(
            model_name='server',
            name='additional_plugins',
            field=models.JSONField(blank=True, default=list, help_text='Lista de plugins adicionales a instalar (nombres de archivos)'),
        ),
        migrations.AddField(
            model_name='server',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key para autenticación del plugin/mod (se genera automáticamente)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='install_essentials',
            field=models.BooleanField(default=False, help_text='Instalar EssentialsX (comandos esenciales) - solo para Bukkit/Spigot/Paper'),
        ),
        migrations.AddField(
            model_name='server',
            name='install_fabric_api',
            field=models.BooleanField(default=False, help_text='Instalar Fabric API (requerido para mods de Fabric)'),
        ),
        migrations.AddField(
            model_name='server',
            name='install_forge',
            field=models.BooleanField(default=False, help_text='Instalar Forge (requerido para mods de Forge)'),
        ),
        migrations.AddField(
            model_name='server',
            name='install_jei',
            field=models.BooleanField(default=False, help_text='Instalar JEI/REI (Just Enough Items) - ver recetas de items'),
        ),
        migrations.AddField(
            model_name='server',
            name='install_luckperms',
            field=models.BooleanField(default=False, help_text='Instalar LuckPerms (sistema de permisos)'),
        ),
        migrations.AddField(
            model_name='server',
            name='install_more_inventory',
            field=models.BooleanField(default=False, help_text='Instalar Más Mochila (More Inventory) - aumenta inventario del jugador'),
        ),
        migrations.AddField(
            model_name='server',
            name='install_proximity_chat',
            field=models.BooleanField(default=False, help_text='Instalar chat de proximidad (voice/chat por distancia)'),
        ),
        migrations.AddField(
            model_name='server',
            name='install_spark',
            field=models.BooleanField(default=True, help_text='Instalar Spark (profiling y análisis de rendimiento)'),
        ),
        migrations.AddField(
            model_name='server',
            name='install_worldedit',
            field=models.BooleanField(default=False, help_text='Instalar WorldEdit (edición de mundos)'),
        ),
        migrations.AddField(
            model_name='server',
            name='install_wthit',
            field=models.BooleanField(default=False, help_text='Instalar WTHIT (What The Hell Is That) - información de bloques'),
        ),
        migrations.AddField(
            model_name='server',
            name='minecraft_version',
            field=models.CharField(default='latest', help_text='Versión de Minecraft (ej: 1.20.1, latest)', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('vanilla', 'Vanilla (oficial)'), ('fabric', 'Fabric'), ('forge', 'Forge'), ('bukkit', 'Bukkit'), ('spigot', 'Spigot'), ('paper', 'Paper')], default='vanilla', help_text='Tipo de servidor Minecraft', max_length=20),
        ),
    ]
