# Generated by Django 4.2.7 on 2025-12-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_minecraftversion_server_additional_mods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Email del usuario para envío de token de contraseña', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='minecraftuser',
            name='password_set_token',
            field=models.CharField(blank=True, help_text='Token para establecer contraseña', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='minecraftuser',
            name='password_set_token_expires',
            field=models.DateTimeField(blank=True, help_text='Expiración del token (24 horas)', null=True),
        ),
        migrations.AlterField(
            model_name='minecraftuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Activo solo después de establecer contraseña'),
        ),
        migrations.AlterField(
            model_name='minecraftuser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='minecraftuser',
            name='salt',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
