# Generated by Django 4.2.7 on 2025-12-29 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0004_add_email_password_token_to_minecraft_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_name', models.CharField(help_text="Nombre del mod (ej: 'cobblemon', 'jei', 'wthit')", max_length=255, unique=True)),
                ('display_name', models.CharField(help_text="Nombre para mostrar (ej: 'Cobblemon', 'JEI', 'WTHIT')", max_length=255)),
                ('config_format', models.CharField(choices=[('json', 'JSON'), ('yaml', 'YAML'), ('properties', 'Properties'), ('toml', 'TOML'), ('txt', 'Texto plano')], default='json', help_text='Formato del archivo de configuración', max_length=20)),
                ('config_file_path', models.CharField(help_text="Ruta relativa del archivo de configuración (ej: 'config/cobblemon.json', 'config/jei/jei-client.toml')", max_length=500)),
                ('default_config', models.TextField(blank=True, help_text='Configuración por defecto (contenido del archivo)')),
                ('description', models.TextField(blank=True, help_text='Descripción del mod y su configuración')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activa esta plantilla?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Configuración de Mod',
                'verbose_name_plural': 'Plantillas de Configuración de Mods',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ServerModConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_content', models.TextField(blank=True, help_text='Configuración personalizada para este servidor (si está vacío, usa la plantilla)')),
                ('is_enabled', models.BooleanField(default=True, help_text='¿Está habilitada esta configuración en el servidor?')),
                ('last_applied', models.DateTimeField(blank=True, help_text='Última vez que se aplicó esta configuración al servidor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mod_configs', to=settings.AUTH_USER_MODEL)),
                ('mod_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_configs', to='server.modconfigtemplate')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_configs', to='server.server')),
            ],
            options={
                'verbose_name': 'Configuración de Mod por Servidor',
                'verbose_name_plural': 'Configuraciones de Mods por Servidor',
                'ordering': ['server', 'mod_template__display_name'],
                'unique_together': {('server', 'mod_template')},
            },
        ),
    ]
