# Generated by Django 4.2.7 on 2025-12-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_add_mod_config_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre del mod/plugin (ej: 'cobblemon', 'luckperms')", max_length=255, unique=True)),
                ('display_name', models.CharField(help_text="Nombre para mostrar (ej: 'Cobblemon', 'LuckPerms')", max_length=255)),
                ('mod_type', models.CharField(choices=[('mod', 'Mod (Fabric/Forge)'), ('plugin', 'Plugin (Bukkit/Spigot/Paper)')], help_text='Tipo: Mod (Fabric/Forge) o Plugin (Bukkit/Spigot/Paper)', max_length=20)),
                ('compatible_vanilla', models.BooleanField(default=False, help_text='Compatible con Vanilla (solo plugins nativos)')),
                ('compatible_fabric', models.BooleanField(default=False, help_text='Compatible con Fabric (solo mods)')),
                ('compatible_forge', models.BooleanField(default=False, help_text='Compatible con Forge (solo mods)')),
                ('compatible_bukkit', models.BooleanField(default=False, help_text='Compatible con Bukkit (solo plugins)')),
                ('compatible_spigot', models.BooleanField(default=False, help_text='Compatible con Spigot (solo plugins)')),
                ('compatible_paper', models.BooleanField(default=False, help_text='Compatible con Paper (solo plugins)')),
                ('description', models.TextField(blank=True, help_text='Descripción del mod/plugin')),
                ('modrinth_id', models.CharField(blank=True, help_text='ID en Modrinth (para mods) o SpigotMC (para plugins)', max_length=255)),
                ('curseforge_id', models.CharField(blank=True, help_text='ID en CurseForge', max_length=255)),
                ('download_url', models.URLField(blank=True, help_text='URL directa de descarga (opcional)')),
                ('version', models.CharField(blank=True, help_text="Versión recomendada (ej: '1.20.1', 'latest')", max_length=50)),
                ('is_popular', models.BooleanField(default=False, help_text='¿Es un mod/plugin popular?')),
                ('is_recommended', models.BooleanField(default=False, help_text='¿Es recomendado para nuevos servidores?')),
                ('category', models.CharField(blank=True, help_text="Categoría (ej: 'pokemon', 'voice', 'economy', 'permissions')", max_length=100)),
                ('config_file_path', models.CharField(blank=True, help_text="Ruta del archivo de configuración (ej: 'config/cobblemon.json')", max_length=500)),
                ('config_format', models.CharField(choices=[('json', 'JSON'), ('yaml', 'YAML'), ('properties', 'Properties'), ('toml', 'TOML'), ('txt', 'Texto plano')], default='json', help_text='Formato del archivo de configuración', max_length=20)),
                ('default_config', models.TextField(blank=True, help_text='Configuración por defecto (opcional)')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activo en el pool?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mod/Plugin del Pool',
                'verbose_name_plural': 'Mods/Plugins del Pool',
                'ordering': ['-is_recommended', '-is_popular', 'display_name'],
            },
        ),
    ]
