# Generated by Django 4.2.7 on 2026-01-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_add_memory_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='modpool',
            name='file_path',
            field=models.CharField(blank=True, help_text="Ruta del archivo .jar en el servidor (ej: '/data/mods_pool/cobblemon.jar')", max_length=500),
        ),
    ]
