# Generated by Django 4.2.7 on 2026-01-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_modpool_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='additional_ports',
            field=models.JSONField(blank=True, default=list, help_text="Puertos adicionales a exponer. Formato: [{'port': 24454, 'protocol': 'udp', 'host_port': 24454}]"),
        ),
    ]
