# Generated by Django 4.2.7 on 2026-01-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_server_additional_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.IntegerField(default=25565, help_text='Puerto del servidor Minecraft'),
        ),
    ]
